#version: '3.8'

services:
  playwright:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./allure-results:/app/allure-results
    environment:
      - CI=true