version: "3.8"

services:
  playwright:
    build:https://github.com/sainiboyz1/playwright-docker/blob/master/docker-compose.yml
      context: ./docker
      dockerfile: Dockerfile
    container_name: playwrightdocker-playwright-1
    volumes:
      - .:/app
      - ./test-results:/app/test-results
    working_dir: /app

