version: "3.8"

services:
  playwright:
    build:
      context: .
    container_name: playwrightdocker-playwright-1
    volumes:
      - .:/app
      - ./test-results:/app/test-results
    working_dir: /app

