version: '3.8'

services:
  playwright:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./allure-results:/app/allure-results
      - ./test-results:/app/test-results  # Mount for test results
    environment:
      - CI=true
    working_dir: /app
